[tool.poetry]
name = "bromley-bin-reminder"
version = "0.1.0"
description = ""
authors = ["Matt Holubinka <meholubinka@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4 = "^4.12.3"
requests = "^2.32.3"
selenium = "^4.26.1"
lxml = {extras = ["html-clean"], version = "^5.3.0"}
schedule = "^1.2.2"
pytz = "^2024.2"
webdriver-manager = "^4.0.2"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.10.0"
mypy = "^1.13.0"
ruff = "^0.7.2"
pre-commit = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
